### ISSUE TITLE
Are you sure you need the 'forEach()'?

### ISSUE THREAD

**Issue by techhasid** [dovigoldstein/PCS-Class#1]
https://github.com/dovigoldstein/PCS-Class/blob/6ced119f4a4c10dff69ad104cd942bc9561dcf26/HW_97/snake/snake2.js#L135

Any specific reason you put the 'forEach()'? 
Couldn't you have just done:
`            if (appleX === snake.x && appleY === snake.y) {
                placeApple();
            }`
with out the **forEach**?

**Comment by dovigoldstein** [comment]
The snake is made up of an array of points. You must check that the apple will not be placed on any of those points.

**Comment by techhasid** [comment]
Got it, ok.
